### ISSUE TITLE
"Alternative" maven plugin / approach

### ISSUE THREAD

**Issue by h3xstream** [victims/victims-enforcer-legacy#30]
Hi victims team,
I am using actively the **victims-cve-db** unfortunately the enforcer plugin failed on most of my tests. I have create a alternative maven plugin that does verification directly based on versions rather than the intermediary hashes.
- https://github.com/h3xstream/maven-security-versions

I am posting this mainly for full disclosure. I am not looking to do a fork or create something bigger. If the victims team is interested, it could become a "official" victims client.

Smalls differences/additions:
- No dependency to victi.ms website
- No configuration needed
- HTML report

**Comment by ashcrow** [comment]
Nice! So you are pulling the victims data from github?

**Comment by h3xstream** [comment]
It is loading the archive of the master branch from github. It is reading the atom feed prior re-downloading the db. [Ref: [VictimsDbLoader.java](https://github.com/h3xstream/maven-security-versions/blob/master/src/main/java/com/h3xstream/maven/victims/VictimsDbLoader.java#L48)]

The license will probably have to be [AGPL](https://github.com/victims/victims-cve-db/blob/master/LICENSE) because of the dependency to the victims-cve-db project.

**Comment by jasinner** [comment]
Sorry it took so long to comment on this, but do you think we could move this under the 'victims' Github organization?

**Comment by h3xstream** [comment]
@jasinner No problem.
At the same time, we could change the package name to `com.redhat.victims` and release the plugin to Maven Central.

**Comment by h3xstream** [comment]
@jasinner 
I am trying to do the migration I get : "You don’t have the permission to create repositories on victims"

**Comment by jasinner** [comment]
I've added you as a project owner for victims. So you should be able to add the repository now. 
It would be good if we could also change the package name, thanks.

**Comment by h3xstream** [comment]
Same error.

I get this warning when I click on the plus sign : 
![2017-11-21 19_59_29-create a new repository](https://user-images.githubusercontent.com/593130/33104499-8986e830-cef6-11e7-9799-40a7d393ec49.png)

I will contact GitHub support.

**Comment by jasinner** [comment]
sorry, please try again. Seems I did update your membership status correctly the first time.

**Comment by h3xstream** [comment]
Done ! https://github.com/victims/maven-security-versions
